version: '3.8'
services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: slope_search
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: