services:
  client:
    build:
      context: ./client
    ports:
      - "4173:4173"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    command: --local-infile=1
    environment:
      DOCKER: "true"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - ./notebook/data:/data
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: